/**
 * errorReporter — single integration point for client-side error reporting.
 *
 * The whole codebase calls `reportError(...)` from ErrorBoundary's `onError`
 * callback (and anywhere else we want to surface a caught exception). When
 * we wire Sentry / Datadog / Honeycomb, we change THIS file — not 50 call
 * sites.
 *
 * Behavior today:
 *   - dev: console.error with the error ID + context for grep-friendly logs
 *   - prod: console.error (visible in Vercel function logs) + best-effort POST
 *           to /api/internal/errors (the endpoint doesn't exist yet — the
 *           POST silently no-ops on 404 so the user is never affected)
 *
 * Sentry swap path: replace the body of `reportError` with `Sentry.captureException`.
 */

export interface ErrorReportPayload {
  /** Stable category, e.g. 'render', 'submit', 'fetch'. */
  context: string;
  /** Generated by ErrorBoundary; correlates with the user-facing fallback. */
  errorId?: string;
  /** Free-form metadata: route, walletAddress (lower-cased!), etc. */
  meta?: Record<string, unknown>;
}

/**
 * Report a caught error. Never throws. Caller code keeps running.
 */
export function reportError(error: Error, payload: ErrorReportPayload): void {
  const isDev = process.env.NODE_ENV !== 'production';
  const tag = `[errorReporter:${payload.context}]`;
  const errorIdSuffix = payload.errorId ? ` (${payload.errorId})` : '';

  // Always log — Vercel function logs are searchable by errorId.
  // eslint-disable-next-line no-console
  console.error(`${tag}${errorIdSuffix}`, {
    message: error.message,
    name: error.name,
    stack: isDev ? error.stack : undefined,
    meta: payload.meta,
  });

  if (isDev) return;

  // Production: best-effort POST to /api/internal/errors. Fire-and-forget —
  // the endpoint validates shape + rate-limits by IP + logs via the structured
  // logger. We never await it; failures are silently ignored.
  try {
    const body = JSON.stringify({
      message: error.message,
      name: error.name,
      stack: error.stack,
      ...payload,
    });
    if (typeof fetch !== 'undefined') {
      void fetch('/api/internal/errors', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body,
        keepalive: true,
      }).catch(() => {
        // Silent — never let the error reporter throw.
      });
    }
  } catch {
    // Should never happen but makes lint happy + bullet-proofs the caller.
  }
}
